#!/bin/bash

# Run this code from the directory the file is. We
# call this directory WORKSPACE. The script required
# the variables HADOOP_HOME and MAHOUT_HOME
#
# This script is thought to run on top of Hadoop in
# *standalone* mode
#
# 1. Inside WORKSPACE create 'lib' directory and
# copy 'mahout_feature.jar' there
#
# 2. Inside WORKSPACE create 'data' directory and
# download the example dataset
#   http://penglab.janelia.org/proj/mRMR/test_nci9_s3.csv
#
# 3. Note: running the script the "output" and "temp"
# directories will be removed

# START configuration

WORKSPACE_DIR=`pwd`

OUTPUT_DIR="${WORKSPACE_DIR}/output"
LIB_DIR="${WORKSPACE_DIR}/lib"
DATA_DIR="${WORKSPACE_DIR}/data"

FEATURE_SELECTED=3

DATASET=rankingdataset.csv

# END configuration

rm -r ${OUTPUT_DIR}
rm -r temp/

# Job

${MAHOUT_HOME}/bin/mahout hadoop jar ${LIB_DIR}/mahout_feature.jar \
	org.apache.mahout.feature.mionc.MIonCDriver \
        -i ${DATA_DIR}/${DATASET} -o ${OUTPUT_DIR}/mrmr -t 1 -nc 10 -nr 10000
